### ISSUE TITLE
Kentor.AuthServices.Internal.PendingAuthnRequests within a web farm

### ISSUE THREAD

**Issue by akiander** [KentorIT/authservices#315] opened 2015-10-22 14:11 UTC
In looking at the **PendingAuthnRequests** class, it relies on a static Dictionary: 

     private static readonly Dictionary<Saml2Id, StoredRequestState> pendingAuthnRequest = new Dictionary<Saml2Id, StoredRequestState>();

This is where important state that must be present after an authentication response comes back from an Identity Provider. If it's not there, then the entire authentication event will fail. 

So this static class should work fine for this purpose when there is only one web server, but in a load balanced, multi-server web farm, shouldn't this fail if you land on a different server when returning from the Identity Provider?

If you agree, I would be happy to build an alternative implementation since I need this now, but would like some guidance up front on where and how you want that accomplished. Please advise.

**Comment by albinsunnanbo** [comment] 2015-10-22 17:20
Dupe of #98 ?

**Comment by AndersAbel** [comment] 2015-10-23 09:34
Yes, it's a duplicate of #98.

**Closed by AndersAbel** 2015-10-23 09:35 UTC
