### ISSUE TITLE
kentor(okta) integration in mvc error

### ISSUE THREAD

**Issue by abilash1205** [KentorIT/authservices#721] opened 2017-05-11 10:11 UTC
i am getting below error

The signing algorithm http://www.w3.org/2001/04/xmldsig-more#rsa-sha256 is weaker than the minimum accepted http://www.w3.org/2000/09/xmldsig#rsa-sha1.

i used below kentor authservices in okta

http://developer.okta.com/blog/2016/03/22/use-kentor-authservices-with-okta/

in mvc i used latest kentor  V0.21.2

visual studio 2012 framework 4.5

can please help on this

**Comment by abilash1205** [comment] 2017-05-11 10:13
i check https://github.com/KentorIT/authservices also but its also getting same error

  <kentor.authServices entityId="http://localhost:53761/AuthServices" returnUrl="http://localhost:53761/Home" publicOrigin="http://localhost:53761/AuthServices/SignIn">
    
    <identityProviders>
      <add entityId="http://www.okta.com/exkaet221dhc01PD80h7" signOnUrl="https://dev-128899.oktapreview.com/app/techdev128899_test12_1/exkaet221dhc01PD80h7/sso/saml" allowUnsolicitedAuthnResponse="true" binding="HttpRedirect">
        <signingCertificate fileName="~/App_Data/okta.cer" />
      </add>
    </identityProviders>
  </kentor.authServices>

  <system.identityModel>
    <identityConfiguration>
      <audienceUris>
        <add value="http://localhost:53761/AuthServices" />
      </audienceUris>
    </identityConfiguration>
  </system.identityModel>

  <system.identityModel.services>
    <federationConfiguration>
      <cookieHandler requireSsl="false" name="MvctestoktaAuth" />
    </federationConfiguration>
  </system.identityModel.services>

**Comment by GerwinNL** [comment] 2017-05-11 11:18
You must upgrade to 4.6.2 for this version of AuthServices. 
See https://github.com/KentorIT/authservices/blob/master/doc/Configuration.md#signingalgorithm-attribute

**Comment by explunit** [comment] 2017-05-11 11:59
Duplicate of #717

**Closed by explunit** 2017-05-11 11:59 UTC

**Comment by abilash1205** [comment] 2017-05-11 12:06
hai GerwinNL i added but still i getting
public static class AuthConfig
{
public static void RegisterAuth()
{
Kentor.AuthServices.Configuration.Options.GlobalEnableSha256XmlSignatures();
}
}
