### ISSUE TITLE
Bug: Redirect binding creates an incorrect URL

### ISSUE THREAD

**Issue by Peperud** [KentorIT/authservices#294] opened 2015-08-20 01:31 UTC
Doesn't seem to detect that there are already other parameters in the url and just slaps "?SAMLRequest=..." at the end

example: 
https://sso.connect.pingidentity.com/sso/idp/SSO.saml2?idpid=5a07d61f-4afe-43a0-857a-3e65568458ae?SAMLRequest=hZFPb4MwDMXvlfodUO6Q8CdAo9IJrZdKnSaVbYfdUjBrpBJYHKrx7Qds1dbLdvSzfvZ79hplcw46kff2pA%2Fw3gNa56M5axRfnYz0RotWokKhZQMobCmK%2FGEvAo%2BJzrS2Ldsz%2Bc38jUhEMFa1mji7bUZUVfp1AJzXdb1aRTWEx7A6siA5Ml6xEJKYOC9gcAQyMvIjhdjDTqOV2o4S87nLUjdgT8wX%2FkoE%2FJU42zGG0tLO1MnaDgWliK1XtlpDab1O6TdVgbbKDqPYTE2qqo4WxaM3p7gbK1VlXLKkiv3ajWQNbhRK5qY8kW4IMedxGvFUAnHya6j7VmPfgCnAXFQJz4f9z351kdq1ozPfG1B5gzSVmncP0%2FXp1Q6dqm8eaV4i2SwXjrOeXYk5vdlMM%2F8faU2Pdk1vyOXiW7h9%2BuYT

**Comment by AndersAbel** [comment] 2015-08-20 19:11
Duplicate of #132

**Closed by AndersAbel** 2015-08-20 19:11 UTC
Labels: bug, duplicate
